### PR TITLE
Polishing: use readonly arrays

### PR DESCRIPTION
**Pull request by johnsonr**

### CODE REVIEW

**Comment by ddgenome** [comment]
Won't this break the implementations of, for example, `addExtentionPacks` since it modifies the `extensionPacks` array?

**Comment by ddgenome** [comment]
Although I guess if the TypeScript compiler is not complaining…

**Comment by ddgenome** [comment]
It's strange that the interface defines `ReadOnlyArray`s

https://github.com/atomist/sdm/blob/2226a276a62cecdfe5911b72fa8e6f295d9dd040/lib/api/machine/ListenerRegistrationManager.ts#L114

but the compiler allows the implementation to use regular arrays that can be mutated

https://github.com/atomist/sdm/blob/2226a276a62cecdfe5911b72fa8e6f295d9dd040/lib/api-helper/machine/ListenerRegistrationManagerSupport.ts#L40

and are mutated

https://github.com/atomist/sdm/blob/2226a276a62cecdfe5911b72fa8e6f295d9dd040/lib/api-helper/machine/ListenerRegistrationManagerSupport.ts#L71

**Comment by johnsonr** [comment]
I assume that the implementation is seeing the mutable type. Whereas callers through the interface are constrained, which is the goal.

**Comment by ddgenome** [comment]
So the interface constrains the consumer and the implementer different ways. Intriguing.

**Pull request merged**
