### PR TITLE
Re-export client exports used by SDMs

### LINKED ISSUE #544: Re-export useful automation-client exports from SDM
To make using this package easier, export useful items from automation-client from this project.

This might allow us to move automation-client into a dependency in this project and no longer require projects that use this package to also depend on automation-client themselves.

### PR DESCRIPTION
**Pull request by ddgenome**
Make client invisible by re-exporting all client objects used by
downstream projects.  Move client to a dependency so packages that
depend on SDM do not need to depend directly on client.

**BREAKING** Rename Slack message functions error, warning, and
success to be more descriptive to avoid conflicting with more
fundamental client exports.

Some client exports are now scoped, so update usage as appropriate.
Fix imports to import from client rather than sdm exports of client.

Closes #544

### CODE REVIEW

**Comment by ddgenome** [comment]
Resolved

**Comment by jessitron** [comment]
Moving client to a regular dependency can be a problem
sdm-core and sdm-local also depend on client. If they resolve to a different version of client then they'll be in two places on the filesystem.
automation-client contains global variables. Logging, and some state. When we have two versions of client you get two versions of those.
That's why client is a peer dependency, so that none of sdm-core, sdm-local, sdm (and all the packs!!!) have their own version of client.

**Comment by ddgenome** [comment]
Since sdm will now re-export everything in client used by downstream projects, downstream projects will no longer depend on automation-client, or even be aware of it. Depending on sdm will be enough.

**Comment by ddgenome** [comment]
Proposed change in direction:

-   Indices define the package's customer-facing interface and so should exclude things used only by sdm, sdm-core, and sdm-local
-   We are not going to re-export automation-client exports from sdm at present because
    -   It creates problems for auto-importing in IDEs
    -   Projects would import from one package and need to read TypeDoc from another
    -   It is too breaking a change to be done this close to 1.0.0 release

We will review these differences in usage and update the indices in automation-client, sdm, and sdm-core.

**Comment by ddgenome** [comment]
I've gone through all the exports added to the automation-client index, and all of them appear as imports in non-"internal" packages. So all that needs to be done is remove the additional indices added here.

**Comment by ddgenome** [comment]
Well, that and resolve conflicts.

**Pull request merged**
